### ISSUE TITLE
Node number limits

### ISSUE THREAD

**Issue by cse578group29** [networkop/k8s-topo#18]
Hello, is there any specific reason to set up the limits of nodes as 256*3 in the example/builder/builder ? Can k8s-topo support larger numbers of nodes? Thank you.

    if num>256*3:
        print("Number of nodes cannot exceed {}".format(256*3))
        exit(0)

**Comment by networkop** [comment]
Yes, there's no upper limit for pods. The 256*3 limit comes from the maximum number of IPs in all 3 IPv4 demo ranges:
https://github.com/networkop/k8s-topo/blob/master/examples/builder/builder#L12

**Comment by cse578group29** [comment]
Thanks for the reply.
