### ISSUE TITLE
ImagePullBackOff error for switches

### ISSUE THREAD

**Issue by cse578group29** [networkop/k8s-topo#19]
When creating switches, the status of pod is "ImagePullBackOff" . The host and qrtr pods are running. Any suggestions to solve this issue?

**Comment by networkop** [comment]
What's the name of the image that's causing this?

**Comment by cse578group29** [comment]
It seems that there is no image of switch. Is there any resource available for layer-2 switch?

**Comment by networkop** [comment]
yep, you can check either `ghcr.io/nokia/srlinux` or `frrouting/frr` or you can download ceos from arista.com.

**Comment by cse578group29** [comment]
Thank you!
